package com.bodoczky.fittracker.model.enums;

public enum ExerciseCategory {
    BENCH_PRESS,
    SQUAT,
    DEADLIFT,
    SINGLE_LEG_KNEE,
    SINGLE_LEG_HIP,
    HORIZONTAL_PULL,
    VERTICAL_PULL,
    HORIZONTAL_PRESS,
    VERTICAL_PRESS,
    ACCESSORY_CHEST,
    ACCESSORY_SHOULDER,
    ACCESSORY_BICEPS,
    ACCESSORY_TRICEPS,
    ACCESSORY_GLUTES,
    ACCESSORY_HAMSTRINGS,
    ACCESSORY_QUADS,
    CORE,
    SHOULDER_HEALTH,
    HIP_HEALTH,
    WARMUP,
    FLEXIBILITY
}
